### ISSUE TITLE
colab removes last 2 amino acids

### ISSUE THREAD

**Issue by HWaymentSteele** [aqlaboratory/rgn2#5]
Hi,

The RGN2 colab notebook removes the last 2 residues of the input sequence. The input sequence in `run.json` still contains the last 2 residues, but the `fulinit.pdb` is missing them. 

I would like to benchmark RGN2 in comparison to other methods, and so I could hack a fix by adding two alanines or something, but I am not sure that will faithfully represent RGN2's embedding. Thanks!

**Comment by christinaflo** [comment]
Hi, this is actually expected behavior. Due to the Frenet-Serret framing strategy, in order to construct a frame at a given residue, two residues following it are needed to define the torsion and curvature angles required to create the rotation matrix. Therefore, we exclude the last two residues where we cannot construct a frame.
